### ISSUE TITLE
Error: Cannot find module 'ws' in version 5.0.0

### ISSUE THREAD

**Issue by jarrietas** [1Forge/javascript-forex-quotes#7]
```
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jarrieta/Desktop/personal/channel/node_modules/forex-quotes/lib/SocketClient.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/home/jarrieta/Desktop/personal/channel/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (/home/jarrieta/Desktop/personal/channel/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

Version `4.0.1` works fine.

**Comment by jarrietas** [comment]
Tested with `5.0.2` and still getting the same Cannot find module 'ws'. Not sure this one should be closed.

**Comment by bricktownseo** [comment]
I'm sorry @jarrietas, please try with 5.0.3

**Comment by jarrietas** [comment]
Working like a charm in 5.0.3 :). Thanks for the quick response !
